language: bash

services:
  - docker

env:
  global:
    - LATEST_TAG=4.1
  matrix:
    - VARNISH_VER=4.1.9 TAG=4.1 EXTRA_TAG=4

script:
  - cd ./"${VARNISH_VER:0:1}"
  - make && make test

after_success:
  - bash "${TRAVIS_BUILD_DIR}/travis-release.sh"

notifications:
  on_failure: never
  slack:
    secure: |
      jnIsjARKvmeTTlx/1KUwD282u7WMgqRnFxXD4VyTy6tgu9+tWLDQtZDao8TyUpFSF6xjMNuE59sASJAgdPa7a60KUlsQE+hmbPjqNLzY5yHKOJfjGrYqKLB3DmTxxmNzJmvt/xqCuip4rFtdqSFVaK6bj+4R9XL45vL5PaEYNF8i5j+NJUf+nejW1NlYY3dxyNYYQb95Nngvpn7E2Sie5Yr/GA35F5EIsbZMYkCDQbbKjtdq+QOrsjs3jyeTIvAQuVLg9Wx4067s7EXAevWsp2M0ol7xYkkN3+j8X4S0HrKp8RHm5JXvhRLmi2h4OVF6DHPZTCSPqqVM+PnDs+ycsnvDVO4rvefFGS+7FGnkL1CbNqD/rNLs2dulgCCQ8zljCHv9MIUBLfEMP8YAVWceRWjn1fYVYv7r+ErCJAVKcC5m9VuuJxhXdxNHemZ+TeIxZiqVJxPbkKWqG0nJUROfMEDhqWkJeK4CPV8XHSDSUolSDX73B3Fq2UHvCyFiZmW8dEU+EgIsOPVAnh+35I2PO8dCbvuHIwfyYK2H9tomN6Pg90n93dnKmagHEYGLnrMYtvJ6HeGWCNCVmPzpBHtC4yVS4PFgFURWnyZmkPz+mpHOHzW1fYLXuY5+Cw0Tz0qRZYQRNsxhDAVUhwy4NJR9Ah6SR6fTxaCE3KP9B+1+upw=
